# Generated by Django 3.2 on 2021-04-18 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deposits', '0003_rename_deposit_type_deposit_deposittype'),
        ('clients', '0004_auto_20210418_0558'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditType', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContractNumber', models.CharField(max_length=8, unique=True)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('period', models.IntegerField()),
                ('cash', models.IntegerField()),
                ('percent', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('creditType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credits.credittype')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deposits.currency')),
            ],
        ),
    ]
