# Generated by Django 3.2 on 2021-04-18 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credit',
            old_name='ContractNumber',
            new_name='contractNumber',
        ),
    ]
