# Generated by Django 3.2 on 2021-04-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='ContractNumber',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
