# Generated by Django 3.2 on 2021-04-18 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0002_alter_deposit_contractnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='deposit_type',
            new_name='depositType',
        ),
    ]
