# Generated by Django 3.2 on 2021-04-18 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0003_rename_deposit_type_deposit_deposittype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='ContractNumber',
            new_name='contractNumber',
        ),
    ]
