# Generated by Django 3.2 on 2021-04-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='homePhone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='mobilePhone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='passportNumberId',
            field=models.CharField(error_messages={'unique': 'Клиент с таким идентификационым номером уже существует'}, max_length=14, unique=True),
        ),
    ]
