# Generated by Django 3.2 on 2021-04-12 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='birth_place',
            new_name='birthPlace',
        ),
    ]
