# Generated by Django 3.2 on 2021-04-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20210413_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='homePhone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
