# Generated by Django 3.2 on 2021-04-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_homephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(blank=True, error_messages={'unique': 'Клиент с такой электронной почтой уже существует'}, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='homePhone',
            field=models.CharField(blank=True, error_messages={'unique': 'Клиент с таким домашним номером уже существует'}, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='mobilePhone',
            field=models.CharField(blank=True, error_messages={'unique': 'Клиент с таким мобильным номером уже существует'}, max_length=20, null=True, unique=True),
        ),
    ]
